config/routes.rb
Rails.application.routes.draw do
  resources :secaos
  resources :zonas
  resources :categoria
  devise_for :users
  root to: "solicitantes#index"
  resources :andamento_solicitacao_enviadas
  resources :andamento_solicitacao_recebidas
  resources :estados
  resources :funcionarios
  resources :municipios
  resources :processos
  resources :solicitacao_enviadas
  resources :solicitacao_recebidas
  resources :solicitantes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/andamento_solicitacao_enviada.rb
class AndamentoSolicitacaoEnviada < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoria.rb
class Categoria < ApplicationRecord
    has_many :solicitantes
end

app/models/estado.rb
class Estado < ApplicationRecord
    has_many :solicitantes
end

app/models/estado_civil.rb
class EstadoCivil < ApplicationRecord
    has_many :solicitantes
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/municipio.rb
class Municipio < ApplicationRecord
    has_many :solicitantes
end

app/models/processo.rb
class Processo < ApplicationRecord
end

app/models/secao.rb
class Secao < ApplicationRecord
  belongs_to :zona
  has_many :solicitantes
end

app/models/solicitacao_enviada.rb
class SolicitacaoEnviada < ApplicationRecord
end

app/models/solicitante.rb
class Solicitante < ApplicationRecord
    belongs_to :estado_civil
    belongs_to :zona
    belongs_to :secao
    belongs_to :municipio
    belongs_to :estado
    belongs_to :categoria

    scope :by_zona, -> (zona) {
        where(zona_id: zona) if zona
    }

    scope :by_secao, -> (secao) {
        where(secao_id: secao) if secao
    }

    scope :by_categoria, -> (categoria) {
        where(categoria_id: categoria) if categoria
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
end

app/models/zona.rb
class Zona < ApplicationRecord
    has_many :secaos

end

app/controllers/andamento_solicitacao_enviadas_controller.rb
class AndamentoSolicitacaoEnviadasController < ApplicationController
  before_action :set_andamento_solicitacao_enviada, only: [:show, :edit, :update, :destroy]

  # GET /andamento_solicitacao_enviadas
  # GET /andamento_solicitacao_enviadas.json
  def index
    @andamento_solicitacao_enviadas = AndamentoSolicitacaoEnviada.all
  end

  # GET /andamento_solicitacao_enviadas/1
  # GET /andamento_solicitacao_enviadas/1.json
  def show
  end

  # GET /andamento_solicitacao_enviadas/new
  def new
    @andamento_solicitacao_enviada = AndamentoSolicitacaoEnviada.new
  end

  # GET /andamento_solicitacao_enviadas/1/edit
  def edit
  end

  # POST /andamento_solicitacao_enviadas
  # POST /andamento_solicitacao_enviadas.json
  def create
    @andamento_solicitacao_enviada = AndamentoSolicitacaoEnviada.new(andamento_solicitacao_enviada_params)

    respond_to do |format|
      if @andamento_solicitacao_enviada.save
        format.html { redirect_to @andamento_solicitacao_enviada, notice: 'Andamento solicitacao enviada was successfully created.' }
        format.json { render :show, status: :created, location: @andamento_solicitacao_enviada }
      else
        format.html { render :new }
        format.json { render json: @andamento_solicitacao_enviada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /andamento_solicitacao_enviadas/1
  # PATCH/PUT /andamento_solicitacao_enviadas/1.json
  def update
    respond_to do |format|
      if @andamento_solicitacao_enviada.update(andamento_solicitacao_enviada_params)
        format.html { redirect_to @andamento_solicitacao_enviada, notice: 'Andamento solicitacao enviada was successfully updated.' }
        format.json { render :show, status: :ok, location: @andamento_solicitacao_enviada }
      else
        format.html { render :edit }
        format.json { render json: @andamento_solicitacao_enviada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /andamento_solicitacao_enviadas/1
  # DELETE /andamento_solicitacao_enviadas/1.json
  def destroy
    @andamento_solicitacao_enviada.destroy
    respond_to do |format|
      format.html { redirect_to andamento_solicitacao_enviadas_url, notice: 'Andamento solicitacao enviada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_andamento_solicitacao_enviada
      @andamento_solicitacao_enviada = AndamentoSolicitacaoEnviada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def andamento_solicitacao_enviada_params
      params.require(:andamento_solicitacao_enviada).permit(:data, :descricao, :observacao, :funcionario_id, :solicitacao_enviada_id, :criado_por, :atualizado_por)
    end
end

app/helpers/andamento_solicitacao_enviadas_helper.rb
module AndamentoSolicitacaoEnviadasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def usuario_atual
        if user_signed_in?
            usuario_atual = current_user.email
        end
    end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/helpers/secaos_helper.rb
module SecaosHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/andamento_solicitacao_enviadas/_form.html.erb
<%= form_with(model: andamento_solicitacao_enviada, local: true) do |form| %>
  <% if andamento_solicitacao_enviada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(andamento_solicitacao_enviada.errors.count, "error") %> prohibited this andamento_solicitacao_enviada from being saved:</h2>

      <ul>
      <% andamento_solicitacao_enviada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data, id: :andamento_solicitacao_enviada_data %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :andamento_solicitacao_enviada_descricao %>
  </div>

  <div class="field">
    <%= form.label :observacao %>
    <%= form.text_area :observacao, id: :andamento_solicitacao_enviada_observacao %>
  </div>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.number_field :funcionario_id, id: :andamento_solicitacao_enviada_funcionario_id %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_enviada_id %>
    <%= form.number_field :solicitacao_enviada_id, id: :andamento_solicitacao_enviada_solicitacao_enviada_id %>
  </div>

  <div class="field">
    <%= form.label :criado_por %>
    <%= form.number_field :criado_por, id: :andamento_solicitacao_enviada_criado_por %>
  </div>

  <div class="field">
    <%= form.label :atualizado_por %>
    <%= form.number_field :atualizado_por, id: :andamento_solicitacao_enviada_atualizado_por %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/andamento_solicitacao_enviadas/edit.html.erb
<h1>Editing Andamento Solicitacao Enviada</h1>

<%= render 'form', andamento_solicitacao_enviada: @andamento_solicitacao_enviada %>

<%= link_to 'Show', @andamento_solicitacao_enviada %> |
<%= link_to 'Back', andamento_solicitacao_enviadas_path %>

app/views/andamento_solicitacao_enviadas/index.html.erb
<h1>Andamento Solicitacao Enviadas</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Descricao</th>
      <th>Observacao</th>
      <th>Funcionario</th>
      <th>Solicitacao enviada</th>
      <th>Criado por</th>
      <th>Atualizado por</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @andamento_solicitacao_enviadas.each do |andamento_solicitacao_enviada| %>
      <tr>
        <td><%= andamento_solicitacao_enviada.data %></td>
        <td><%= andamento_solicitacao_enviada.descricao %></td>
        <td><%= andamento_solicitacao_enviada.observacao %></td>
        <td><%= andamento_solicitacao_enviada.funcionario_id %></td>
        <td><%= andamento_solicitacao_enviada.solicitacao_enviada_id %></td>
        <td><%= andamento_solicitacao_enviada.criado_por %></td>
        <td><%= andamento_solicitacao_enviada.atualizado_por %></td>
        <td><%= link_to 'Show', andamento_solicitacao_enviada %></td>
        <td><%= link_to 'Edit', edit_andamento_solicitacao_enviada_path(andamento_solicitacao_enviada) %></td>
        <td><%= link_to 'Destroy', andamento_solicitacao_enviada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Andamento Solicitacao Enviada', new_andamento_solicitacao_enviada_path %>

app/views/andamento_solicitacao_enviadas/new.html.erb
<h1>New Andamento Solicitacao Enviada</h1>

<%= render 'form', andamento_solicitacao_enviada: @andamento_solicitacao_enviada %>

<%= link_to 'Back', andamento_solicitacao_enviadas_path %>

app/views/andamento_solicitacao_enviadas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @andamento_solicitacao_enviada.data %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @andamento_solicitacao_enviada.descricao %>
</p>

<p>
  <strong>Observacao:</strong>
  <%= @andamento_solicitacao_enviada.observacao %>
</p>

<p>
  <strong>Funcionario:</strong>
  <%= @andamento_solicitacao_enviada.funcionario_id %>
</p>

<p>
  <strong>Solicitacao enviada:</strong>
  <%= @andamento_solicitacao_enviada.solicitacao_enviada_id %>
</p>

<p>
  <strong>Criado por:</strong>
  <%= @andamento_solicitacao_enviada.criado_por %>
</p>

<p>
  <strong>Atualizado por:</strong>
  <%= @andamento_solicitacao_enviada.atualizado_por %>
</p>

<%= link_to 'Edit', edit_andamento_solicitacao_enviada_path(@andamento_solicitacao_enviada) %> |
<%= link_to 'Back', andamento_solicitacao_enviadas_path %>