config/routes.rb
Rails.application.routes.draw do
  resources :secaos
  resources :zonas
  resources :categoria
  devise_for :users
  root to: "solicitantes#index"
  resources :andamento_solicitacao_enviadas
  resources :andamento_solicitacao_recebidas
  resources :estados
  resources :funcionarios
  resources :municipios
  resources :processos
  resources :solicitacao_enviadas
  resources :solicitacao_recebidas
  resources :solicitantes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categoria.rb
class Categoria < ApplicationRecord
    has_many :solicitantes
end

app/models/estado.rb
class Estado < ApplicationRecord
    has_many :solicitantes
end

app/models/estado_civil.rb
class EstadoCivil < ApplicationRecord
    has_many :solicitantes
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

app/models/municipio.rb
class Municipio < ApplicationRecord
    has_many :solicitantes
end

app/models/processo.rb
class Processo < ApplicationRecord
end

app/models/secao.rb
class Secao < ApplicationRecord
  belongs_to :zona
  has_many :solicitantes
end

app/models/solicitacao_enviada.rb
class SolicitacaoEnviada < ApplicationRecord
end

app/models/solicitacao_recebida.rb
class SolicitacaoRecebida < ApplicationRecord
end

app/models/solicitante.rb
class Solicitante < ApplicationRecord
    belongs_to :estado_civil
    belongs_to :zona
    belongs_to :secao
    belongs_to :municipio
    belongs_to :estado
    belongs_to :categoria

    scope :by_zona, -> (zona) {
        where(zona_id: zona) if zona
    }

    scope :by_secao, -> (secao) {
        where(secao_id: secao) if secao
    }

    scope :by_categoria, -> (categoria) {
        where(categoria_id: categoria) if categoria
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
end

app/models/zona.rb
class Zona < ApplicationRecord
    has_many :secaos

end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :data_aniversario, :criado_por, :atualizado_por, :sexo, :endereco, :email, :bairro, :municipio_id, :data_admissao, :data_desligamento, :cep, :telefone, :celular, :cpf, :matricula)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def usuario_atual
        if user_signed_in?
            usuario_atual = current_user.email
        end
    end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/helpers/secaos_helper.rb
module SecaosHelper
end

app/helpers/solicitantes_helper.rb
module SolicitantesHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario, local: true) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :funcionario_nome %>
  </div>

  <div class="field">
    <%= form.label :data_aniversario %>
    <%= form.date_select :data_aniversario, id: :funcionario_data_aniversario %>
  </div>

  <div class="field">
    <%= form.label :criado_por %>
    <%= form.number_field :criado_por, id: :funcionario_criado_por %>
  </div>

  <div class="field">
    <%= form.label :atualizado_por %>
    <%= form.number_field :atualizado_por, id: :funcionario_atualizado_por %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :funcionario_sexo %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco, id: :funcionario_endereco %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :funcionario_email %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :funcionario_bairro %>
  </div>

  <div class="field">
    <%= form.label :municipio_id %>
    <%= form.number_field :municipio_id, id: :funcionario_municipio_id %>
  </div>

  <div class="field">
    <%= form.label :data_admissao %>
    <%= form.date_select :data_admissao, id: :funcionario_data_admissao %>
  </div>

  <div class="field">
    <%= form.label :data_desligamento %>
    <%= form.date_select :data_desligamento, id: :funcionario_data_desligamento %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep, id: :funcionario_cep %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :funcionario_telefone %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular, id: :funcionario_celular %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :funcionario_cpf %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula, id: :funcionario_matricula %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<h1>Funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data aniversario</th>
      <th>Criado por</th>
      <th>Atualizado por</th>
      <th>Sexo</th>
      <th>Endereco</th>
      <th>Email</th>
      <th>Bairro</th>
      <th>Municipio</th>
      <th>Data admissao</th>
      <th>Data desligamento</th>
      <th>Cep</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Cpf</th>
      <th>Matricula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.data_aniversario %></td>
        <td><%= funcionario.criado_por %></td>
        <td><%= funcionario.atualizado_por %></td>
        <td><%= funcionario.sexo %></td>
        <td><%= funcionario.endereco %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.bairro %></td>
        <td><%= funcionario.municipio_id %></td>
        <td><%= funcionario.data_admissao %></td>
        <td><%= funcionario.data_desligamento %></td>
        <td><%= funcionario.cep %></td>
        <td><%= funcionario.telefone %></td>
        <td><%= funcionario.celular %></td>
        <td><%= funcionario.cpf %></td>
        <td><%= funcionario.matricula %></td>
        <td><%= link_to 'Show', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Data aniversario:</strong>
  <%= @funcionario.data_aniversario %>
</p>

<p>
  <strong>Criado por:</strong>
  <%= @funcionario.criado_por %>
</p>

<p>
  <strong>Atualizado por:</strong>
  <%= @funcionario.atualizado_por %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @funcionario.sexo %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @funcionario.bairro %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @funcionario.municipio_id %>
</p>

<p>
  <strong>Data admissao:</strong>
  <%= @funcionario.data_admissao %>
</p>

<p>
  <strong>Data desligamento:</strong>
  <%= @funcionario.data_desligamento %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @funcionario.cep %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @funcionario.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @funcionario.celular %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @funcionario.cpf %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @funcionario.matricula %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>